[package]
name = "deliverable"
version = "0.1.0"
description = "Options on tokenized equities that survive corporate actions and the closing bell"
edition.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib"]
name = "deliverable"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
anchor-debug = []
custom-heap = []
custom-panic = []


[dependencies]
anchor-lang = "1.2.0"
anchor-spl = "1.2.0"
pyth-solana-receiver-sdk = "2.0.0"

[dev-dependencies]
litesvm = "0.10.0"
solana-account = "3.2.0"
solana-instruction = "3.0.0"
solana-keypair = "3.0.1"
solana-message = "3.0.1"
solana-pubkey = "3.0.0"
solana-signer = "3.0.0"
solana-transaction = "3.0.2"


[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }
